// Generated by gencpp from file custom_msg_pkg/age.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_PKG_MESSAGE_AGE_H
#define CUSTOM_MSG_PKG_MESSAGE_AGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msg_pkg
{
template <class ContainerAllocator>
struct age_
{
  typedef age_<ContainerAllocator> Type;

  age_()
    : year(0)
    , month(0)
    , day(0)  {
    }
  age_(const ContainerAllocator& _alloc)
    : year(0)
    , month(0)
    , day(0)  {
  (void)_alloc;
    }



   typedef int8_t _year_type;
  _year_type year;

   typedef int8_t _month_type;
  _month_type month;

   typedef int8_t _day_type;
  _day_type day;





  typedef boost::shared_ptr< ::custom_msg_pkg::age_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg_pkg::age_<ContainerAllocator> const> ConstPtr;

}; // struct age_

typedef ::custom_msg_pkg::age_<std::allocator<void> > age;

typedef boost::shared_ptr< ::custom_msg_pkg::age > agePtr;
typedef boost::shared_ptr< ::custom_msg_pkg::age const> ageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg_pkg::age_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg_pkg::age_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msg_pkg::age_<ContainerAllocator1> & lhs, const ::custom_msg_pkg::age_<ContainerAllocator2> & rhs)
{
  return lhs.year == rhs.year &&
    lhs.month == rhs.month &&
    lhs.day == rhs.day;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msg_pkg::age_<ContainerAllocator1> & lhs, const ::custom_msg_pkg::age_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msg_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msg_pkg::age_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg_pkg::age_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_pkg::age_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_pkg::age_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_pkg::age_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_pkg::age_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg_pkg::age_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b467db0ba69e6a9712f4aa2325c633b3";
  }

  static const char* value(const ::custom_msg_pkg::age_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb467db0ba69e6a97ULL;
  static const uint64_t static_value2 = 0x12f4aa2325c633b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg_pkg::age_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg_pkg/age";
  }

  static const char* value(const ::custom_msg_pkg::age_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg_pkg::age_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 year\n"
"int8 month\n"
"int8 day\n"
;
  }

  static const char* value(const ::custom_msg_pkg::age_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg_pkg::age_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.year);
      stream.next(m.month);
      stream.next(m.day);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct age_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg_pkg::age_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg_pkg::age_<ContainerAllocator>& v)
  {
    s << indent << "year: ";
    Printer<int8_t>::stream(s, indent + "  ", v.year);
    s << indent << "month: ";
    Printer<int8_t>::stream(s, indent + "  ", v.month);
    s << indent << "day: ";
    Printer<int8_t>::stream(s, indent + "  ", v.day);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_PKG_MESSAGE_AGE_H
